<a href="https://colab.research.google.com/github/Cherednikov77/goit-algo-fp/blob/main/Homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
M = np.array([[100, 150, 200], [50, 100, 150], [0, 50, 100]])
E = np.array([[20, 30, 40], [10, 20 ,30], [5, 10, 15]])
contrast_M = M * 0.5
brightless_M = M + 25
blended_M = 0.8 * M + 0.2 * E
print('M:\n', M)

print("n1. (M*0.5):\n", contrast_M)
print("n2. (M+25):\n", brightless_M)
print("n3. (0.8*M+0.2*E):\n", blended_M)



M:
 [[100 150 200]
 [ 50 100 150]
 [  0  50 100]]
n1. (M*0.5):
 [[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]
n2. (M+25):
 [[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]
n3. (0.8*M+0.2*E):
 [[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]


In [15]:
from os import name
import numpy as np
u = np.array([8, 2, 5])
movies = {"film A (action)": np.array([9, 1, 2]), "film B (comedy)": np.array([1, 9, 8]), "film C (drama)": np.array([7, 2, 6])}
def cosin_similarity(v1, v2):
  dot_product = np.dot(v1, v2)
  norm_v1 = np.linalg.norm(v1)
  norm_v2 = np.linalg.norm(v2)
  return dot_product
similarity = {}
for name, v_movie in movies.items():
  score = cosin_similarity(u, v_movie)
  similarity[name] = score
  print(f"the some {name}: {score: .4f}")

best_movie = max(similarity, key = similarity.get)
print("-" * 30)
print(f"{best_movie} {similarity[best_movie]:.4f}")



the some film A (action):  84.0000
the some film B (comedy):  66.0000
the some film C (drama):  90.0000
------------------------------
film C (drama) 90.0000


In [30]:
import numpy as np
A = np.array([[4,1,1], [4, 1, 2], [6, 2, 4]]).T
b = np.array([460, 130, 240])
determinant_A = np.linalg.det(A)
print(f"matrix A:{determinant_A:.2f}")
if determinant_A != 0:
  print(f"determinant_A is not 0.\n")
  x = np.linalg.solve(A, b)
  check = np.dot(A, x)

  drone_types = ["scout", "kamikadze", "cargo"]
  print("result:")

  for i in range(len(drone_types)):
    print(f"{drone_types [i]}: {x[i]} things")
  print(f"{check}")
  print(f"cost: {b}")






matrix A:-2.00
determinant_A is not 0.

result:
scout: 20.0 things
kamikadze: 50.0 things
cargo: 30.0 things
[460. 130. 240.]
cost: [460 130 240]


In [36]:
import numpy as np
t = np.array([1, 2, 3, 4, 5])
y = np.array([22, 28, 37, 45, 53])
A = np.vstack([t, np.ones(len(t))]).T
coeffs = np.linalg.lstsq(A, y)
k, b = coeffs[0]
print(f"{k:.2f} + {b:.2f}")
t_next = 6
y_pred = k * t_next + b
print("{y_pred:.2f}%")
t_crash = (100-b)/k
print(f"100% server load after {t_crash:.1f} hours")


7.90 + 13.30
{y_pred:.2f}%
100% server load after 11.0 hours
